# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4739011b1b80918a3a4a1b7435d276ae56837193f1dafe78393bb722b177f03eefcfc85a5ed0bc6492c4c7d399ca8b5bee7804a2b3a51b90dd76acd77a18d019

test:
  secret_key_base: dd4a8a92162e2bb6c626ad8df4099b4da233a572cfc48bac4878b77e2aead392f42f70c17ee90384823c59cb191663dabfac2822728649239baab588a328831e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
